const countries = [
  { "name": "Albanien", "capital": "Tirana" },
  { "name": "Andorra", "capital": "Andorra" },
  { "name": "Belgien", "capital": "Brüssel" },
  { "name": "Bulgarien", "capital": "Sofia" },
  { "name": "Dänemark", "capital": "Kopenhagen" },
  { "name": "Deutschland", "capital": "Berlin" },
  { "name": "Estland", "capital": "Tallinn" },
  { "name": "Finnland", "capital": "Helsinki" },
  { "name": "Frankreich", "capital": "Paris" },
  { "name": "Griechenland", "capital": "Athen" },
  { "name": "Irland", "capital": "Dublin" },
  { "name": "Island", "capital": "Reykjavík" },
  { "name": "Italien", "capital": "Rom" },
  { "name": "Kasachstan", "capital": "Astana" },
  { "name": "Kosovo", "capital": "Pristina" },
  { "name": "Kroatien", "capital": "Zagreb" },
  { "name": "Lettland", "capital": "Riga" },
  { "name": "Liechtenstein", "capital": "Vaduz" },
  { "name": "Litauen", "capital": "Vilnius" },
  { "name": "Luxemburg", "capital": "Luxemburg" },
  { "name": "Malta", "capital": "Valletta" },
  { "name": "Mazedonien", "capital": "Skopje" },
  { "name": "Republik Moldau", "capital": "Chișinău" },
  { "name": "Montenegro", "capital": "Podgorica" },
  { "name": "Niederlande", "capital": "Amsterdam" },
  { "name": "Norwegen", "capital": "Oslo" },
  { "name": "Österreich", "capital": "Wien" },
  { "name": "Polen", "capital": "Warschau" },
  { "name": "Portugal", "capital": "Lissabon" },
  { "name": "Rumänien", "capital": "Bukarest" },
  { "name": "Russland", "capital": "Moskau" },
  { "name": "San Marino", "capital": "San Marino" },
  { "name": "Schweden", "capital": "Stockholm" },
  { "name": "Schweiz", "capital": "Bern" },
  { "name": "Serbien", "capital": "Belgrad" },
  { "name": "Slowakei", "capital": "Bratislava" },
  { "name": "Slowenien", "capital": "Ljubljana" },
  { "name": "Spanien", "capital": "Madrid" },
  { "name": "Tschechien", "capital": "Prag" },
  { "name": "Türkei", "capital": "Ankara" },
  { "name": "Ukraine", "capital": "Kiew" },
  { "name": "Ungarn", "capital": "Budapest" },
  { "name": "Vereinigtes Königreich", "capital": "London" },
  { "name": "Weißrussland", "capital": "Minsk" }
];

export default countries